services:
  app:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/beer_fridge
    depends_on:
      - db
    command: sh -c "pnpm install && pnpm prisma generate && pnpm dev"

  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=beer_fridge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: